version: '3.8'

services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/tracker_db
#      - SPRING_DATASOURCE_USERNAME=tracker
#      - SPRING_DATASOURCE_PASSWORD=tracker123
#      - SPRING_RABBITMQ_HOST=rabbitmq
#      - SPRING_RABBITMQ_PORT=5672
#      - SPRING_RABBITMQ_USERNAME=tracker
#      - SPRING_RABBITMQ_PASSWORD=track123
#      - SPRING_REDIS_HOST=redis
#      - SPRING_REDIS_PORT=6379
#    depends_on:
#      - db
#      - redis
#      - rabbitmq

  db:
    image: postgres:latest
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=craft-demo-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json
    environment:
      - RABBITMQ_DEFAULT_USER=tracker
      - RABBITMQ_DEFAULT_PASS=track123
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management.load_definitions /etc/rabbitmq/definitions.json
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres-data:
